/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3PptFc3JZHn
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { useRef } from "react";

export function Upload() {
  const inputRef = useRef<HTMLInputElement>(null);
  const handleOpen = () => {
    inputRef.current?.click();
  };

  const uploadFile = () => {
    if (inputRef.current?.files === null) return;
    var formdata = new FormData();
    formdata.append("file", inputRef.current.files[0], "deoxys.csv");

    var requestOptions = {
      method: "POST",
      body: formdata,
    };

    fetch("http://34.93.69.211:5000/upload_file", requestOptions)
      .then((response) => response.text())
      .then((result) => console.log(result))
      .catch((error) => console.log("error", error));
  };

  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <div>Upload CSV</div>
        {/* <p className="mt-1 prose-sm">Drag and drop a CSV file to upload.</p> */}
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {/* <div className="border-dashed border border-gray-200 rounded-lg w-full p-6 flex items-center justify-center gap-4 dark:border-gray-800"> */}
        {/* <span className="text-sm text-gray-500">
            Drag and drop your file here or
            <Button size="sm" className="ms-2" onClick={handleOpen}>
              Select a file
            </Button>
          </span> */}
        {/* </div> */}
        <div className="flex flex-col gap-2 space-y-3">
          <div className="grid w-full items-center gap-0.5 space-y-2">
            <Label htmlFor="file">File</Label>
            <Input ref={inputRef} id="file" type="file" accept=".csv" />
          </div>
          <Button onClick={uploadFile}>Upload</Button>
        </div>
        {/* <progress
          className="progress progress-primary w-full"
          value="70"
          max="100"
        ></progress> */}
      </CardContent>
    </Card>
  );
}
